services:
  - type: web
    name: ats-sales-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        value: postgresql://ats_to2n_user:ixDs4gP0kpcwDfffaYASiVjJMIK7B7k0@dpg-d9kugflaeets73a88qhg-a/ats_to2n
      - key: JWT_SECRET
        value: thuyghtssvngtfgukhju,guy655443sgsbfdbgggnfhfnhmrgv
      - key: CORS_ORIGIN
        value: https://brand-promoter-prod.vercel.app

